# Generated by Django 5.1.7 on 2025-03-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pihome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
    ]
