# Generated by Django 5.1.7 on 2025-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pihome', '0002_remove_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
