# Generated by Django 5.1.7 on 2025-03-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pihome', '0003_action_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='message',
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
