# Generated by Django 5.1.7 on 2025-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pihome', '0004_remove_action_message_alter_action_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
